# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bonodev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hotel-miranda-dashboard-backend
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
functions:
  app:
    handler: dist/server.handler
    environment:
      MONGODB_URI: "mongodb+srv://admin:Zv9yfyvuLDqudCwT@cluster0.3pqaekg.mongodb.net/Hotel_Dashboard?retryWrites=true&w=majority"
    events:
    - http: ANY /
    - http: ANY /{proxy+}
